config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  get '/about' => 'pages#about'
  
  root 'pages#home'
  resources :contacts
  resources :lectures

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    validates :password, presence: true
    

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
    validates :subject, presence: true
    validates :day, presence: true
end

app/models/plan.rb
class Plan <ActiveRecord::Base
    has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  attr_accessor :stripe_card_token
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, source: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
   def new
    @contact = Contact.new
   end
    
   def create
       @contact = Contact.new(contact_params)
       
       if @contact.save
           name = params[:contact][:name]
           email = params[:contact][:email]
           password = params[:contact][:password]
           
           ContactMailer.contact_email(name, email, password).deliver
           flash[:success] = 'Sign in successful'
           redirect_to new_contact_path
       else
           flash[:danger] = 'Fail DA'
           redirect_to new_contact_path
       end
   end
   
   private
       def contact_params
           params.require(:contact).permit(:name, :email, :comments)
       end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def new
      @lecture = Lecture.new
  end
  
  def create
      @lecture = Lecture.new(lecture_params)
      
      if @lecture.save
          flash[:success] = 'Class added'
          redirect_to new_lecture_path
      else
          flash[:danger] = 'Fail Da'
          redirect_to new_lecture_path
      end
  end
  
  private
    def lecture_params
        params.require(:lecture).permit(:subject, :day, :tutor)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
        @basic_plan = Plan.find(1)
        @pro_plan = Plan.find(2)
    end
    
    def about
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :only_current_user
  
  def new
    # form where a user can fill out their own profile.
    @user = User.find( params[:user_id] )
    @profile = Profile.new
  end
  def create 
    @user = User.find( params[:user_id] )
    @profile = @user.build_profile(profile_params)
    if @profile.save
      flash[:success] = "Profile Updated!"
      redirect_to user_path( params[:user_id] )
    else
      render action: :new
    end
  end
  
  def edit
     @user = User.find( params[:user_id] )
     @profile = @user.profile
  end
  
  def update
      @user = User.find( params[:user_id] )
      @profile = @user.profile
      if @profile.update_attributes(profile_params)
        flash[:success] = "Profile Updated!"
        redirect_to user_path( params[:user_id] )
      else
        render action: :edit
      end
  end
  

  
  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
    end
    
    def only_current_user
      @user = User.find( params[:user_id] )
      redirect_to(root_url) unless @user == current_user
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :select_plan, only: :new
  
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
  end
end

private
  def select_plan
    unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
      flash[:notice] = "Please select a membership plan to sign up."
      redirect_to root_url
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    def show
        @user = User.find(params[:id])
    end
    
    def index
        @users = User.includes(:profile)
        @user = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/classes/new.html.erb
<div class = "row">
    <div class="col-md-4 col-md-offset-4">
        <div class = "well">
        <%= form_for (@newclass) do |f| %>
           <div class = "form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control" %>
            </div>
            
           <div class = "form-group">
                <%= f.label :email %>
                <%= f.email_field :email, class: "form-control" %>
            </div>
            
           <div class = "form-group">            
                <%= f.label :password %>
                <%= f.password_field :password, class: "form-control" %>
           </div>
           
           <%= f.submit 'Submit', class: "btn btn-default" %>
        <% end %>
        </div>
    </div>
    
</div>

app/views/contacts/new.html.erb
<div class = "row">
    <div class="col-md-4 col-md-offset-4">
        <div class = "well">
        <%= form_for @contact do |f| %>
           <div class = "form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control" %>
            </div>
            
           <div class = "form-group">
                <%= f.label :email %>
                <%= f.email_field :email, class: "form-control" %>
            </div>
            
           <div class = "form-group">            
                <%= f.label :password %>
                <%= f.password_field :password, class: "form-control" %>
           </div>
           
           <%= f.submit 'Submit', class: "btn btn-default" %>
        <% end %>
        </div>
    </div>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scheduleit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to root_path, class: 'navbar-brand' do %>
           <i class = "fa fa-mortar-board"></i> 
           ScheduleIT
        <% end %> 
         
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <li><a href="/users/sign_up">Sign in</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Students <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/lectures/new">Schedule a class</a></li>
            <li><a href="#">Drop a class</a></li>
            <li><a href="#">Calender</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Tutoring preferences</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Settings</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
        <% end %>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact Us", new_contact_path %></li>
        <li><%= link_to "Lecture", new_lecture_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tutors <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Add time card</a></li>
            <li><a href="#">Remove time card</a></li>
            <li><a href="#">Calender</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Settings</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<div class = "container">
  <% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
  <%= yield %>
</div>
</body>

app/views/lecture_email/lecture_email.html.erb
<!DOCTYPE html>

<html>
    <head>
    </head>
    
    <body>
        <p>Sign in details received <%= "#{ @subject }, #{ @day }, #{ @tutor }" %> </p>
    </body>
    
</html>

app/views/lectures/new.html.erb
<div class = "row">
    <div class="col-md-4 col-md-offset-4">
        <div class = "well">
        <%= form_for Lecture.new do |f| %>
           <div class = "form-group">
                <%= f.label :Subject %>
                <%= f.text_field :subject, class: "form-control" %>
            </div>
            
           <div class = "form-group">
                <%= f.label :day %>
                <%= f.text_field :day, class: "form-control" %>
            </div>
            
           <div class = "form-group">            
                <%= f.label :tutor %>
                <%= f.text_field :tutor, class: "form-control" %>
           </div>
           
           <%= f.submit 'Submit', class: "btn btn-default" %>
        <% end %>
        </div>
    </div>
    
</div>

app/views/pages/about.html.erb
<h2>About us</h2>

<p>Hi!
Scedule it is an interactive envirment created to make scheduling easy for students, tutors and admins alike. Add, drop or rechedule any class you want with the click of a button.
To know more about us <a href="/contacts/new">click here.</a>
Our goal is save precious time and effort of students and teachers, who can communicate and organize their schedule easier than ever before.
Its completely free and easy, to make the best of it <a href="/users/sign_up">Sign in</a>
.You can also checkout our mobile application <a href="#">here</a></p>

app/views/pages/home.html.erb
<%= link_to "Customize your profile", new_user_profile_path(current_user) if current_user %>

<div class= "jumbotron text-center">
    <h1>
        Schedule IT!
    </h1>
    <h3>Get your scheduling done as easy as toast!</h3>
    <img src ="http://marylanddancesport.com/wp-content/uploads/sites/10/2014/10/schedule-770x313.jpg"/>
</div>
<% if user_signed_in? %>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Your Profile</h2>
        <% if current_user.profile %>
          <%= link_to "Edit your profile", edit_user_profile_path(current_user), class: 'btn btn-default btn-lg btn-block' %>
          <%= link_to "View your profile", user_path(current_user), class: 'btn btn-default btn-lg btn-block' %>
        <% else %>
          <p>Create your profile so that you can share your information with the community.</p>
          <%= link_to "Create your profile", new_user_profile_path(current_user), class: 'btn btn-default btn-lg btn-block'%>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">The Community</h2>
        <p>Visit the community to meet other developers, entrepreneurs, and investors!</p>
        <%= link_to "Visit the community", users_path, class: 'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
 <% else %>
<div class="row">
  <div class="col-md-6">
    <div class="well">
      <h2 class="text-center">Basic Membership</h2>
      <h4>Free Sign up for students and Tutors.</h4>
      <br/>
      <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="well">
      <h2 class="text-center">Pro Membership</h2>
      <h4>Admins Pro Plans, starting at $100 a month. Explore ScheduleIT for multiple domains and dozens of premium options.</h4>
      <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
    </div>
  </div>
</div>
<% end %>

app/views/profiles/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create Your Profile</h1>
    <p class="text-center">Are you an admin?, click <a href= "#">here</a></p>
    <div class="well">
      <%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :avatar %>
          <%= f.file_field :avatar, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :Subject %>
          <%= f.select :subject, ['Math', 'Science', 'Computers', 'English'], {}, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :phone_number %>
          <%= f.text_field :phone_number, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :contact_email %>
          <%= f.text_field :contact_email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :Tutoring_preferences %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Profile", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Edit your profile</h1>
    <p class="text-center">Are you an admin?, click <a href= "#">here</a></p>
    <div class="well">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create Your Profile</h1>
    <p class="text-center">Are you an admin?, click <a href= "#">here</a></p>
    <div class="well">
      <%= form_for @profile, url: user_profile_path do |f| %>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :Subject %>
          <%= f.select :subject, ['Math', 'Science', 'Computers', 'English'], {}, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :phone_number %>
          <%= f.text_field :phone_number, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :contact_email %>
          <%= f.text_field :contact_email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :Tutoring_preferences %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Profile", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <ul class="list-unstyled">
      <% @users.each do |user| %>
        <% if user.profile %>
        <li>
          <div class="well row <%= cycle('white-bg', '') %>">
            <div class="col-sm-4 text-center">
              <% if user.profile.avatar %>
                <%= link_to user do %>
                  <%= image_tag user.profile.avatar.url(:thumb), class: 'user-index-avatar' %>
                <% end %>
              <% end %>
            </div>
            <div>
              <%= link_to user do %>
                  <% if user.plan_id == 2 %>
                    <span class="label label-danger">ADMIN</span>
                  <% end %>
                <h2><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
              <% end %>
              <p><%= user.profile.subject %></p>
            </div>
          </div>
        </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class ="row">
    <div class = "col-md-3 text center">
        <%= image_tag @user.profile.avatar.url, class: 'user-show-avatar' %>
        <%= image_tag @user.profile.avatar.url %>
    </div>
    <div class = "col-md-3">
    <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
    <h3><%= @user.profile.subject %></h3><br/>
    <%= @user.profile.contact_email %><br/>
    <div class="well profile-description"><%= @user.profile.description %></div>
    
      <%= @user.profile.phone_number %><br/>
    </div>
</div>